# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blogr}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Zwijnenburg"]
  s.date = %q{2011-04-27}
  s.description = %q{Easy blog system for any Rails 3.x project. Simply include the gem in your gemfile and run rake Blogr:migration to generate the needed migrations}
  s.email = %q{daniel@danielz.nl}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/blogr/admin/activities_controller.rb",
    "app/controllers/blogr/admin/blogr_admin_controller.rb",
    "app/controllers/blogr/admin/categories_controller.rb",
    "app/controllers/blogr/admin/medias_controller.rb",
    "app/controllers/blogr/admin/pages_controller.rb",
    "app/controllers/blogr/admin/posts_controller.rb",
    "app/controllers/blogr/admin/sessions_controller.rb",
    "app/controllers/blogr/admin/users_controller.rb",
    "app/controllers/blogr/blogr_controller.rb",
    "app/controllers/blogr/comments_controller.rb",
    "app/controllers/blogr/pages_controller.rb",
    "app/controllers/blogr/posts_controller.rb",
    "app/models/blogr/activity.rb",
    "app/models/blogr/category.rb",
    "app/models/blogr/comment.rb",
    "app/models/blogr/media.rb",
    "app/models/blogr/page.rb",
    "app/models/blogr/post.rb",
    "app/models/blogr/user.rb",
    "app/views/blogr/admin/categories/_form.html.erb",
    "app/views/blogr/admin/categories/edit.html.erb",
    "app/views/blogr/admin/categories/index.html.erb",
    "app/views/blogr/admin/categories/new.html.erb",
    "app/views/blogr/admin/medias/_form.html.erb",
    "app/views/blogr/admin/medias/edit.html.erb",
    "app/views/blogr/admin/medias/index.html.erb",
    "app/views/blogr/admin/medias/new.html.erb",
    "app/views/blogr/admin/pages/_form.html.erb",
    "app/views/blogr/admin/pages/index.html.erb",
    "app/views/blogr/admin/pages/new.html.erb",
    "app/views/blogr/admin/pages/show.html.erb",
    "app/views/blogr/admin/posts/_form.html.erb",
    "app/views/blogr/admin/posts/index.html.erb",
    "app/views/blogr/admin/posts/new.html.erb",
    "app/views/blogr/admin/posts/show.html.erb",
    "app/views/blogr/admin/sessions/dashboard.html.erb",
    "app/views/blogr/admin/sessions/new.html.erb",
    "app/views/blogr/admin/users/_form.html.erb",
    "app/views/blogr/admin/users/new.html.erb",
    "app/views/blogr/comments/_form.html.erb",
    "app/views/blogr/pages/show.html.erb",
    "app/views/blogr/posts/index.html.erb",
    "app/views/blogr/posts/show.html.erb",
    "app/views/blogr/shared/_error_messages.html.erb",
    "app/views/blogr/shared/_menu.html.erb",
    "app/views/layouts/blogr.html.erb",
    "app/views/layouts/blogr_admin.html.erb",
    "config/routes.rb",
    "lib/blogr.rb",
    "lib/blogr/engine.rb",
    "lib/generators/blogr/blogr_generator.rb",
    "lib/generators/blogr/templates/blogr_migration.rb",
    "public/images/bg-button-green.gif",
    "public/images/big_wood.jpg",
    "public/images/css3buttons_backgrounds.png",
    "public/images/css3buttons_icons.png",
    "public/images/delete.png",
    "public/images/edit.png",
    "public/images/stats.png",
    "public/javascripts/blogr_admin.js",
    "public/javascripts/jquery.js",
    "public/javascripts/jquery.tablednd_0_5.js",
    "public/javascripts/rails.js",
    "public/javascripts/tiny_mce/jquery.tinymce.js",
    "public/javascripts/tiny_mce/langs/en.js",
    "public/javascripts/tiny_mce/license.txt",
    "public/javascripts/tiny_mce/plugins/advhr/css/advhr.css",
    "public/javascripts/tiny_mce/plugins/advhr/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/advhr/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/advhr/js/rule.js",
    "public/javascripts/tiny_mce/plugins/advhr/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/advhr/rule.htm",
    "public/javascripts/tiny_mce/plugins/advimage/css/advimage.css",
    "public/javascripts/tiny_mce/plugins/advimage/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/advimage/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/advimage/image.htm",
    "public/javascripts/tiny_mce/plugins/advimage/img/sample.gif",
    "public/javascripts/tiny_mce/plugins/advimage/js/image.js",
    "public/javascripts/tiny_mce/plugins/advimage/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/advlink/css/advlink.css",
    "public/javascripts/tiny_mce/plugins/advlink/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/advlink/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/advlink/js/advlink.js",
    "public/javascripts/tiny_mce/plugins/advlink/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/advlink/link.htm",
    "public/javascripts/tiny_mce/plugins/advlist/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/advlist/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/autolink/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/autolink/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/autoresize/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/autoresize/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/autosave/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/autosave/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/autosave/langs/en.js",
    "public/javascripts/tiny_mce/plugins/bbcode/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/bbcode/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/contextmenu/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/contextmenu/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/directionality/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/directionality/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/emotions/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/emotions/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/emotions/emotions.htm",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-cool.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-cry.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-embarassed.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-foot-in-mouth.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-frown.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-innocent.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-kiss.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-laughing.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-money-mouth.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-sealed.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-smile.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-surprised.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-tongue-out.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-undecided.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-wink.gif",
    "public/javascripts/tiny_mce/plugins/emotions/img/smiley-yell.gif",
    "public/javascripts/tiny_mce/plugins/emotions/js/emotions.js",
    "public/javascripts/tiny_mce/plugins/emotions/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/example/dialog.htm",
    "public/javascripts/tiny_mce/plugins/example/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/example/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/example/img/example.gif",
    "public/javascripts/tiny_mce/plugins/example/js/dialog.js",
    "public/javascripts/tiny_mce/plugins/example/langs/en.js",
    "public/javascripts/tiny_mce/plugins/example/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/fullpage/css/fullpage.css",
    "public/javascripts/tiny_mce/plugins/fullpage/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/fullpage/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/fullpage/fullpage.htm",
    "public/javascripts/tiny_mce/plugins/fullpage/js/fullpage.js",
    "public/javascripts/tiny_mce/plugins/fullpage/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/fullscreen/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/fullscreen/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/fullscreen/fullscreen.htm",
    "public/javascripts/tiny_mce/plugins/iespell/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/iespell/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/inlinepopups/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/inlinepopups/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/alert.gif",
    "public/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/button.gif",
    "public/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/buttons.gif",
    "public/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/confirm.gif",
    "public/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/corners.gif",
    "public/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/horizontal.gif",
    "public/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/vertical.gif",
    "public/javascripts/tiny_mce/plugins/inlinepopups/skins/clearlooks2/window.css",
    "public/javascripts/tiny_mce/plugins/inlinepopups/template.htm",
    "public/javascripts/tiny_mce/plugins/insertdatetime/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/insertdatetime/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/layer/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/layer/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/legacyoutput/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/legacyoutput/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/lists/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/lists/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/media/css/media.css",
    "public/javascripts/tiny_mce/plugins/media/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/media/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/media/js/embed.js",
    "public/javascripts/tiny_mce/plugins/media/js/media.js",
    "public/javascripts/tiny_mce/plugins/media/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/media/media.htm",
    "public/javascripts/tiny_mce/plugins/media/moxieplayer.swf",
    "public/javascripts/tiny_mce/plugins/nonbreaking/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/nonbreaking/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/noneditable/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/noneditable/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/pagebreak/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/pagebreak/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/paste/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/paste/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/paste/js/pastetext.js",
    "public/javascripts/tiny_mce/plugins/paste/js/pasteword.js",
    "public/javascripts/tiny_mce/plugins/paste/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/paste/pastetext.htm",
    "public/javascripts/tiny_mce/plugins/paste/pasteword.htm",
    "public/javascripts/tiny_mce/plugins/preview/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/preview/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/preview/example.html",
    "public/javascripts/tiny_mce/plugins/preview/jscripts/embed.js",
    "public/javascripts/tiny_mce/plugins/preview/preview.html",
    "public/javascripts/tiny_mce/plugins/print/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/print/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/save/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/save/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/searchreplace/css/searchreplace.css",
    "public/javascripts/tiny_mce/plugins/searchreplace/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/searchreplace/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/searchreplace/js/searchreplace.js",
    "public/javascripts/tiny_mce/plugins/searchreplace/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/searchreplace/searchreplace.htm",
    "public/javascripts/tiny_mce/plugins/spellchecker/css/content.css",
    "public/javascripts/tiny_mce/plugins/spellchecker/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/spellchecker/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/spellchecker/img/wline.gif",
    "public/javascripts/tiny_mce/plugins/style/css/props.css",
    "public/javascripts/tiny_mce/plugins/style/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/style/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/style/js/props.js",
    "public/javascripts/tiny_mce/plugins/style/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/style/props.htm",
    "public/javascripts/tiny_mce/plugins/tabfocus/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/tabfocus/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/table/cell.htm",
    "public/javascripts/tiny_mce/plugins/table/css/cell.css",
    "public/javascripts/tiny_mce/plugins/table/css/row.css",
    "public/javascripts/tiny_mce/plugins/table/css/table.css",
    "public/javascripts/tiny_mce/plugins/table/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/table/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/table/js/cell.js",
    "public/javascripts/tiny_mce/plugins/table/js/merge_cells.js",
    "public/javascripts/tiny_mce/plugins/table/js/row.js",
    "public/javascripts/tiny_mce/plugins/table/js/table.js",
    "public/javascripts/tiny_mce/plugins/table/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/table/merge_cells.htm",
    "public/javascripts/tiny_mce/plugins/table/row.htm",
    "public/javascripts/tiny_mce/plugins/table/table.htm",
    "public/javascripts/tiny_mce/plugins/template/blank.htm",
    "public/javascripts/tiny_mce/plugins/template/css/template.css",
    "public/javascripts/tiny_mce/plugins/template/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/template/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/template/js/template.js",
    "public/javascripts/tiny_mce/plugins/template/langs/en_dlg.js",
    "public/javascripts/tiny_mce/plugins/template/template.htm",
    "public/javascripts/tiny_mce/plugins/visualchars/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/visualchars/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/wordcount/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/wordcount/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/abbr.htm",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/acronym.htm",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/attributes.htm",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/cite.htm",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/css/attributes.css",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/css/popup.css",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/del.htm",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/editor_plugin.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/editor_plugin_src.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/ins.htm",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/js/abbr.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/js/acronym.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/js/attributes.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/js/cite.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/js/del.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/js/element_common.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/js/ins.js",
    "public/javascripts/tiny_mce/plugins/xhtmlxtras/langs/en_dlg.js",
    "public/javascripts/tiny_mce/themes/advanced/about.htm",
    "public/javascripts/tiny_mce/themes/advanced/anchor.htm",
    "public/javascripts/tiny_mce/themes/advanced/charmap.htm",
    "public/javascripts/tiny_mce/themes/advanced/color_picker.htm",
    "public/javascripts/tiny_mce/themes/advanced/editor_template.js",
    "public/javascripts/tiny_mce/themes/advanced/editor_template_src.js",
    "public/javascripts/tiny_mce/themes/advanced/image.htm",
    "public/javascripts/tiny_mce/themes/advanced/img/colorpicker.jpg",
    "public/javascripts/tiny_mce/themes/advanced/img/flash.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/icons.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/iframe.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/pagebreak.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/quicktime.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/realmedia.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/shockwave.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/trans.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/video.gif",
    "public/javascripts/tiny_mce/themes/advanced/img/windowsmedia.gif",
    "public/javascripts/tiny_mce/themes/advanced/js/about.js",
    "public/javascripts/tiny_mce/themes/advanced/js/anchor.js",
    "public/javascripts/tiny_mce/themes/advanced/js/charmap.js",
    "public/javascripts/tiny_mce/themes/advanced/js/color_picker.js",
    "public/javascripts/tiny_mce/themes/advanced/js/image.js",
    "public/javascripts/tiny_mce/themes/advanced/js/link.js",
    "public/javascripts/tiny_mce/themes/advanced/js/source_editor.js",
    "public/javascripts/tiny_mce/themes/advanced/langs/en.js",
    "public/javascripts/tiny_mce/themes/advanced/langs/en_dlg.js",
    "public/javascripts/tiny_mce/themes/advanced/link.htm",
    "public/javascripts/tiny_mce/themes/advanced/shortcuts.htm",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/content.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/dialog.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/butt2.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/button-bg.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/buttons.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/down_arrow.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/fade-butt.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/icons.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/items.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/menu-arrow.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/menu-check.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/progress.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/tabs.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/img/toolbarbg.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/cirkuit/ui.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/content.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/dialog.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/img/buttons.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/img/items.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/img/menu_arrow.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/img/menu_check.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/img/progress.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/img/tabs.gif",
    "public/javascripts/tiny_mce/themes/advanced/skins/default/ui.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/highcontrast/content.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/highcontrast/dialog.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/highcontrast/ui.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/o2k7/content.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/o2k7/dialog.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/o2k7/img/button_bg.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/o2k7/img/button_bg_black.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/o2k7/img/button_bg_silver.png",
    "public/javascripts/tiny_mce/themes/advanced/skins/o2k7/ui.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/o2k7/ui_black.css",
    "public/javascripts/tiny_mce/themes/advanced/skins/o2k7/ui_silver.css",
    "public/javascripts/tiny_mce/themes/advanced/source_editor.htm",
    "public/javascripts/tiny_mce/themes/simple/editor_template.js",
    "public/javascripts/tiny_mce/themes/simple/editor_template_src.js",
    "public/javascripts/tiny_mce/themes/simple/img/icons.gif",
    "public/javascripts/tiny_mce/themes/simple/langs/en.js",
    "public/javascripts/tiny_mce/themes/simple/skins/default/content.css",
    "public/javascripts/tiny_mce/themes/simple/skins/default/ui.css",
    "public/javascripts/tiny_mce/themes/simple/skins/o2k7/content.css",
    "public/javascripts/tiny_mce/themes/simple/skins/o2k7/img/button_bg.png",
    "public/javascripts/tiny_mce/themes/simple/skins/o2k7/ui.css",
    "public/javascripts/tiny_mce/tiny_mce.js",
    "public/javascripts/tiny_mce/tiny_mce_popup.js",
    "public/javascripts/tiny_mce/tiny_mce_src.js",
    "public/javascripts/tiny_mce/utils/editable_selects.js",
    "public/javascripts/tiny_mce/utils/form_utils.js",
    "public/javascripts/tiny_mce/utils/mctabs.js",
    "public/javascripts/tiny_mce/utils/validate.js",
    "public/stylesheets/admin.css",
    "public/stylesheets/blogr.css",
    "public/stylesheets/css3buttons.css",
    "public/stylesheets/reset.css",
    "public/stylesheets/tinymce.css"
  ]
  s.homepage = %q{http://github.com/DanielZwijnenburg/blogr}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Easycake blog system for any Rails 3.x project}
  s.test_files = [
    "spec/blogr_spec.rb",
    "spec/controllers/admin/activities_controller_spec.rb",
    "spec/controllers/admin/categories_controller_spec.rb",
    "spec/controllers/admin/pages_controller_spec.rb",
    "spec/controllers/admin/posts_controller_spec.rb",
    "spec/controllers/comments_controller_spec.rb",
    "spec/controllers/pages_controller_spec.rb",
    "spec/controllers/posts_controller_spec.rb",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/migrate/001_create_activities.rb",
    "spec/dummy/db/migrate/002_create_posts.rb",
    "spec/dummy/db/migrate/003_create_comments.rb",
    "spec/dummy/db/migrate/004_create_categories.rb",
    "spec/dummy/db/migrate/005_create_pages.rb",
    "spec/integration/navigation_spec.rb",
    "spec/models/comment_spec.rb",
    "spec/models/page_spec.rb",
    "spec/models/post_spec.rb",
    "spec/request/pages_link_spec.rb",
    "spec/request/posts_link_spec.rb",
    "spec/routing/blogr_routing_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<webrat>, [">= 0"])
      s.add_runtime_dependency(%q<rspec-rails>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_runtime_dependency(%q<capybara>, [">= 0"])
      s.add_runtime_dependency(%q<envjs>, [">= 0"])
      s.add_runtime_dependency(%q<capybara-envjs>, [">= 0"])
      s.add_runtime_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0.7.3"])
      s.add_runtime_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<bcrypt-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-debug>, [">= 0.10.3"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.0.pre3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<webrat>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<envjs>, [">= 0"])
      s.add_dependency(%q<capybara-envjs>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0.7.3"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0.10.3"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre3"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<webrat>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<envjs>, [">= 0"])
    s.add_dependency(%q<capybara-envjs>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0.7.3"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0.10.3"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre3"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

